Translated expansion-tile-sample.md
truongsinh/website pull request #19
Opened 2020-04-05 12:01 UTC by KhanhMaiDang

I've translated /docs/catalog/samples/expansion-tile-sample. Please help me to review.

2020-04-05 17:09 UTC, lightkeima commented on src/docs/catalog/samples/expansion-tile-sample.md
> +Khi hiển thị bên trong một cái có thể cuộn được (a scrollable) mà nó tạo danh sách các mục của nó một
'Khi được hiển thị bên trong một widget cuộn (scrollable widget) tạo ra danh sách của nó một cách lười biếng'

2020-04-05 17:17 UTC, lightkeima commented on src/docs/catalog/samples/expansion-tile-sample.md
> +Khi hiển thị bên trong một cái có thể cuộn được (a scrollable) mà nó tạo danh sách các mục của nó một
lazily ở đây có vẻ đang nói về sự chậm chạp ấy.

2020-04-06 05:42 UTC, KhanhMaiDang commented on src/docs/catalog/samples/expansion-tile-sample.md
> +Khi hiển thị bên trong một cái có thể cuộn được (a scrollable) mà nó tạo danh sách các mục của nó một
Dạ để em sửa lại

2020-04-09 02:07 UTC, truongsinh commented on src/docs/catalog/samples/expansion-tile-sample.md
> +Khi hiển thị bên trong một cái có thể cuộn được (a scrollable) mà nó tạo danh sách các mục của nó một
lazy vs eager https://en.wikipedia.org/wiki/Eager_evaluation vs https://en.wikipedia.org/wiki/Lazy_evaluation

2020-04-09 02:11 UTC, truongsinh requested changes

2020-04-09 02:11 UTC, truongsinh commented on src/docs/catalog/samples/expansion-tile-sample.md
> +Khi hiển thị bên trong một cái có thể cuộn được (a scrollable) mà nó tạo danh sách các mục của nó một
lazy vs eager https://en.wikipedia.org/wiki/Eager_evaluation vs https://en.wikipedia.org/wiki/Lazy_evaluation

2020-04-11 00:47 UTC, truongsinh approved these changes

2020-04-11 00:47 UTC, merged