Vietnamese translation of src/docs/catalog/samples/basic-app-bar.md
truongsinh/website pull request #4
Opened 2020-04-02 03:32 UTC by KhanhMaiDang

2020-04-03 00:40 UTC, truongsinh requested changes
please at least revert the translation on the copyright header. For the inline comment, let's wait to see whether we need to do the translation.

2020-04-03 00:40 UTC, truongsinh commented on src/docs/catalog/samples/basic-app-bar.md
> +// Việc sử dụng đoạn mã nguồn này bị chi phối bởi giấy phép BSD-style được nêu trong
do not translate copyright header

2020-04-08 07:39 UTC, duynht commented
LGTM. I think we can merge @truongsinh

2020-04-08 08:29 UTC, duynht approved these changes

2020-04-08 08:30 UTC, duynht commented on src/docs/catalog/samples/basic-app-bar.md
> +// Việc sử dụng đoạn mã nguồn này bị chi phối bởi giấy phép BSD-style được nêu trong
It's been fixed

2020-04-09 01:57 UTC, merged