Tung tran
truongsinh/website pull request #8
Opened 2020-04-02 16:57 UTC by C2H4Br2

Check giùm nha.

2020-04-03 00:50 UTC, truongsinh commented on firebase.json
> +      { "source": "/go/text-field-characters", "destination": "https://docs.google.com/document/d/1OOFW0PEZf0orBl445YXJ3nfjyKOqZdmeQ6KU3glUh7s/edit?usp=sharing", "type": 301 }
some weird unrelated to translation stuff?

2020-04-03 00:50 UTC, truongsinh commented on src/docs/codelabs/index.md
> +hands-on coding experience. Some codelabs
some weird unrelated to translation stuff?

2020-04-03 00:51 UTC, truongsinh requested changes
some weird unrelated to translation stuff?

2020-04-08 07:46 UTC, duynht commented
@truongsinh should we close this and start a clean PR?

2020-04-09 01:58 UTC, truongsinh commented
Sure, let's close and open a clean new one.

2020-04-09 01:58 UTC, closed without merging